### ISSUE TITLE
Update names of new co-ordinators

### ISSUE THREAD

**Issue by adarshaj** [pclubiitk/pclub.in#70]
https://github.com/pclubiitk/pclub.in/blob/f1cc629d3e9d5d3bb224e9fe1f3f9d2d49b1d6ed/contact.html#L24-L49 Currently reflects earlier co-ordinators.

**Comment by sakshamsharma** [comment]
Also make a new page for past coordinators :smile:

**Comment by adarshaj** [comment]
:p you did not do it for us /cc @aadilh @proneetv @shivanshuag !

**Comment by yashsriv** [comment]
We were waiting for the secys to be selected before updating this page 😛

**Comment by sakshamsharma** [comment]
@adarshaj we made the website :p Changes come incrementally.

**Comment by adarshaj** [comment]
Fixed by #72
